#pragma once

// #define MASTER_LEFT
// #define MASTER_RIGHT
#define EE_HANDS

#define TAPPING_FORCE_HOLD
#define TAPPING_TERM 200

#define OLED_TIMEOUT 1000
#define OLED_FADE_OUT
#define OLED_FADE_OUT_INTERVAL 1

// #define AUTO_SHIFT_TIMEOUT 200
// #define NO_AUTO_SHIFT_SPECIAL
// NO_AUTO_SHIFT_NUMERIC
// NO_AUTO_SHIFT_ALPHA

// Underglow
/*
#undef RGBLED_NUM
#define RGBLED_NUM 14    // Number of LEDs
#define RGBLIGHT_ANIMATIONS
#define RGBLIGHT_SLEEP
*/
